export type AsciiAspect = `${number}/${number}`;

export interface AsciiVariant {
  src: string;
  fps: number;
  columns: number;
  rows: number;
  aspect: AsciiAspect;
  ramp: string;
  posterFrame: number;
  threshold: number;
  whitePoint: number;
  inverted: boolean;
}

// Generated by `pnpm generate:ascii`. Keep this object JSON-compatible.
// prettier-ignore
export const renderAsciiVariants = {
  "bh-01": {
    "src": "/ascii/black-hole-01.json",
    "fps": 30,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 40,
    "threshold": 8,
    "whitePoint": 175,
    "inverted": true
  },
  "bh-02": {
    "src": "/ascii/black-hole-02.json",
    "fps": 25,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 249,
    "threshold": 64,
    "whitePoint": 248,
    "inverted": false
  },
  "bh-03": {
    "src": "/ascii/black-hole-03.json",
    "fps": 24,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 58,
    "threshold": 125,
    "whitePoint": 187,
    "inverted": false
  },
  "clover": {
    "src": "/ascii/clover.json",
    "fps": 24,
    "columns": 96,
    "rows": 48,
    "aspect": "1/1",
    "ramp": " .:-=+X",
    "posterFrame": 42,
    "threshold": 8,
    "whitePoint": 84,
    "inverted": false
  },
  "fire-01": {
    "src": "/ascii/fire-01.json",
    "fps": 23.97601637219404,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 404,
    "threshold": 183,
    "whitePoint": 195,
    "inverted": false
  },
  "fire-02": {
    "src": "/ascii/fire-02.json",
    "fps": 30,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 14,
    "threshold": 207,
    "whitePoint": 226,
    "inverted": false
  },
  "shark": {
    "src": "/ascii/shark.json",
    "fps": 24,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 148,
    "threshold": 77,
    "whitePoint": 168,
    "inverted": false
  }
} as const satisfies Record<string, AsciiVariant>;

export type AsciiRender = keyof typeof renderAsciiVariants;
