export type AsciiAspect = `${number}/${number}`;

export interface AsciiVariant {
  src: string;
  fps: number;
  columns: number;
  rows: number;
  aspect: AsciiAspect;
  ramp: string;
  posterFrame: number;
  threshold: number;
  whitePoint: number;
  inverted: boolean;
  format?: 2;
  crop?: {
    x: number;
    y: number;
    width: number;
    height: number;
    canvasWidth: number;
    canvasHeight: number;
    offsetX: number;
    offsetY: number;
  };
}

// Generated by `pnpm generate:ascii`. Keep this object JSON-compatible.
// prettier-ignore
export const renderAsciiVariants = {
  "bh-01": {
    "src": "/ascii/black-hole-01.json",
    "fps": 30,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 40,
    "threshold": 8,
    "whitePoint": 175,
    "inverted": true
  },
  "bh-02": {
    "src": "/ascii/black-hole-02.json",
    "fps": 25,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 249,
    "threshold": 64,
    "whitePoint": 248,
    "inverted": false
  },
  "bh-03": {
    "src": "/ascii/black-hole-03.json",
    "fps": 24,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 58,
    "threshold": 125,
    "whitePoint": 187,
    "inverted": false
  },
  "clover": {
    "src": "/ascii/clover.json",
    "fps": 24,
    "columns": 96,
    "rows": 48,
    "aspect": "1/1",
    "ramp": " .:-=+X",
    "posterFrame": 42,
    "threshold": 8,
    "whitePoint": 85,
    "inverted": false,
    "format": 2,
    "crop": {
      "x": 9,
      "y": 9,
      "width": 482,
      "height": 482,
      "canvasWidth": 482,
      "canvasHeight": 482,
      "offsetX": 0,
      "offsetY": 0
    }
  },
  "fire-01": {
    "src": "/ascii/fire-01.json",
    "fps": 30,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 14,
    "threshold": 207,
    "whitePoint": 226,
    "inverted": false
  },
  "shark": {
    "src": "/ascii/shark.json",
    "fps": 24,
    "columns": 171,
    "rows": 48,
    "aspect": "16/9",
    "ramp": " .:-=+X",
    "posterFrame": 37,
    "threshold": 8,
    "whitePoint": 175,
    "inverted": false,
    "format": 2,
    "crop": {
      "x": 0,
      "y": 0,
      "width": 1280,
      "height": 720,
      "canvasWidth": 1344,
      "canvasHeight": 756,
      "offsetX": 32,
      "offsetY": 18
    }
  },
  "paragan-wordmark": {
    "src": "/ascii/paragan-wordmark.json",
    "fps": 1,
    "columns": 470,
    "rows": 48,
    "aspect": "1225/250",
    "ramp": " .:-=+X",
    "posterFrame": 0,
    "threshold": 8,
    "whitePoint": 255,
    "inverted": false,
    "format": 2
  }
} as const satisfies Record<string, AsciiVariant>;

export type AsciiRender = keyof typeof renderAsciiVariants;
